name: seaice_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda dependencies
  - python=3.11
  - netcdf4<1.6.1
  - notebook
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - tensorflow
  - seaborn
  - torch
  - torchvision
  - torchaudio
  - icenet
  - torchmetrics
  - lightning
