batch_size: 2

# This data is a holdout set not to be used until we are ready to produce final outputs (e.g. a paper)
predict:
  - start: null
    end: null

# This data is a test set used to compare fully-trained models (e.g. on the project leaderboard)
test:
  - start: 2020-04-24
    end: 2020-04-30

# This data is used for training the model
train:
  - start: 2020-01-01
    end: 2020-03-31

# This data is used for validation during training (e.g. for early stopping etc.)
validate:
  - start: 2020-04-03
    end: 2020-04-23
