# This dataset is used for training the model
train:
  start: None
  end: 2019-12-31

# This dataset is used for validation during training (e.g. for early stopping etc.)
validate:
  start: 2020-01-01
  end: 2020-01-15

# This dataset is a holdout set used to compare fully-trained models (e.g. on a project leaderboard)
test:
  start: 2020-01-16
  end: None
