batch_size: 2

# This data is a holdout set not to be used until we are ready to produce final outputs (e.g. a paper)
predict:
  - start: null
    end: null

# This data is a test set used to compare fully-trained models (e.g. on the project leaderboard)
# Data from 2019
test:
  - start: 2019-01-01
    end: 2019-12-31

# This data is used for training the model
# Data from 2017
train:
  - start: 2017-01-01
    end: 2017-12-31

# This data is used for validation during training (e.g. for early stopping etc.)
# Data from 2018-01
validate:
  - start: 2018-01-01
    end: 2018-01-31
