batch_size: 2

# This dataset is used for training the model
train:
  start: 1979-01-01, 2014-01-01, 2024-01-01
  end: 2012-12-31, 2018-12-31, 2024-12-31

# This dataset is used for validation during training (e.g. for early stopping etc.)
validate:
  start: 2020-01-01
  end: 2022-12-31

# This dataset is a holdout set used to compare fully-trained models (e.g. on a project leaderboard)
test:
  start: 2019-01-01
  end: 2019-12-31

# Holdout: 2013 and 2023 for testing for the paper
