batch_size: 2

# This data is used for training the model
train:
  - start: null
    end: 2012-12-31
  - start: 2014-01-01
    end: 2018-12-31
  - start: 2024-01-01
    end: 2024-12-31

# This data is used for validation during training (e.g. for early stopping etc.)
validate:
  - start: 2020-01-01
    end: 2022-12-31

# This data is a test set used to compare fully-trained models (e.g. on the project leaderboard)
test:
  - start: 2019-01-01
    end: 2019-12-31
