_target_: icenet_mp.models.EncodeProcessDecode

name: cnn-unet-cnn

encoder:
  _target_: icenet_mp.models.encoders.CNNEncoder
  latent_space: [128, 128] # Shape of the latent space

processor:
  _target_: icenet_mp.models.processors.UNetProcessor

decoder:
  _target_: icenet_mp.models.decoders.CNNDecoder
  bounded: false # Whether to bound the output between 0 and 1
