_target_: icenet_mp.models.EncodeProcessDecode

name: naive-unet-naive

encoder:
  _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  latent_space: [432, 432] # Shape of the latent space

processor:
  _target_: icenet_mp.models.processors.UNetProcessor

decoder:
  _target_: icenet_mp.models.decoders.NaiveLinearDecoder
  bounded: false # Whether to bound the output between 0 and 1
