_target_: icenet_mp.models.EncodeProcessDecode

name: piecewise-vit-piecewise

encoder:
  _target_: icenet_mp.models.encoders.PiecewiseEncoder
  latent_space: [192, 192] # Shape of the latent space
  n_conv_blocks: 2 # Number of convolutional blocks to add after encoding

processor:
  _target_: icenet_mp.models.processors.VitProcessor

decoder:
  _target_: icenet_mp.models.decoders.PiecewiseDecoder
  restrict_range: clamp # Method for restricting output range (e.g., clamp, sigmoid, tanh)
  n_conv_blocks: 3 # Number of convolutional blocks to add before decoding
