_target_: icenet_mp.models.EncodeProcessDecode

name: sample

encoder:
  _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  latent_space: [128, 128]

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  start_out_channels: 64

decoder:
  _target_: icenet_mp.models.decoders.NaiveLinearDecoder
