_target_: lightning.pytorch.trainer.trainer.Trainer

# Name of the dataset group containing our prediction target
predict_target: osisaf-south

# PyTorch settings
accelerator: gpu
devices: [0,]
precision: 16-mixed
gradient_clip_val: 0.5
detect_anomaly: false
overfit_batches: 0.0
min_epochs: null
max_epochs: 200
reload_dataloaders_every_n_epochs: 0
num_sanity_val_steps: 8
fast_dev_run: false
accumulate_grad_batches: 16
limit_train_batches: 8000
limit_val_batches: 400
log_every_n_steps: 50
