# Name of the dataset group containing our prediction target
predict_target: osisaf-south

# PyTorch lightning settings
lightning:
  _target_: lightning.pytorch.trainer.trainer.Trainer
  accelerator: auto
  devices: auto
