ci:
  autoupdate_commit_msg: ":rotating_light: Fix pre-commit linting errors"
  autofix_commit_msg: ":rotating_light: Fix pre-commit linting errors"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: ^tests/legacy_metrics.py
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.5"
    hooks:
      # Run the linter
      - id: ruff
        types_or: [python, pyi]
        args: ["--fix", "--show-fixes"]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.0"
    hooks:
      - id: mypy
        args: []
