defaults:
  - callbacks:
    - device_stats
    - ema_weight_averaging
    - metric_summary
    - plotting
    - wandb_metric
  - optimizer: default
  - scheduler: default
  - trainer: default
  - _self_
