# Base config inherited by all other configs
defaults:
  - data: sample
  - evaluate: default
  - loggers:
    - wandb
  - model: naive_unet_naive
  - predict: sic-icenet-2d
  - train: default
  - _self_

base_path: ../base

data:
  land_mask_path: ${base_path}/data/preprocessing/samp-sicsouth-osisaf-25k-2017-2019-24h-v1/IceNetSIC/data/masks/south/masks/land_mask.npy
  active_grid_cell_mask_dir: ${base_path}/data/preprocessing/samp-sicsouth-osisaf-25k-2017-2019-24h-v1/IceNetSIC/data/masks/south/masks