plotting:
  # Callback behaviour
  _target_: icenet_mp.callbacks.PlottingCallback
  frequency:
    epoch: 1
  make_input_plots: false
  make_static_plots: true
  make_video_plots: true
  base_path: ${base_path}
