# Name of the dataset group containing our prediction target
dataset_group: osisaf-south

# Number of future steps to predict
n_forecast_steps: 2

# Number of history steps to use when predicting
n_history_steps: 2
