demo-sicnorth-osisaf-25k-2017-2019-24h-v1:
  name: demo-sicnorth-osisaf-25k-2017-2019-24h-v1
  group_as: osisaf-north
  description: OSISAF sea ice concentration for northern hemisphere
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '2017-01-01T00:00:00'
    end: '2019-12-31T23:00:00'
    frequency: 1d

  preprocessor:
    type: IceNetSIC
    hemisphere: north

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...name}/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/*.nc
