era5-0d5-south-2020-01-24h-v1:
  name: era5-0d5-south-2020-01-24h-v1
  description: 0.5 degree resolution ERA5 for southern hemisphere
  attribution: ECMWF/C3S
  licence: CC-BY-4.0

  dates:
    start: '2020-01-01T00:00:00'
    end: '2020-01-31T23:00:00'
    frequency: 24h

  input:
    join:
    - mars:
        use_cdsapi_dataset: "reanalysis-era5-complete"
        class: ea
        expver: "0001"
        grid: "0.5 / 0.5"
        area: "0/-180/-90/180"  # southern hemisphere
        levtype: sfc
        param:
        - 10u
        - 10v
        - 2d
        - 2t
        - lsm
        - msl
        - sdor
        - skt
        - slor
        - sp
        - tcw
        - z
    - mars:
        use_cdsapi_dataset: "reanalysis-era5-complete"
        class: ea
        expver: "0001"
        grid: "0.5 / 0.5"
        area: "0/-180/-90/180"  # southern hemisphere
        level:
        - 250
        - 500
        - 850
        - 1000
        levtype: pl
        param:
        - u
        - v
        - q
        - t
        - z
    - accumulations:
        use_cdsapi_dataset: "reanalysis-era5-complete"
        accumulation_period: 6
        class: ea
        expver: "0001"
        grid: "0.5 / 0.5"
        area: "0/-180/-90/180"  # southern hemisphere
        param:
        - cp
        - tp

  output:
    original_shape: [181, 720]
