full-sicnorth-osisaf-25k-1979-2024-24h-v1:
  name: full-sicnorth-osisaf-25k-1979-2024-24h-v1
  group_as: osisaf
  description: OSISAF sea ice concentration for northern hemisphere
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '1979-01-01T00:00:00'
    end: '2024-12-31T23:00:00'
    frequency: 1d

  preprocessor:
    type: IceNetSIC
    hemisphere: north

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...name}/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/*.nc
