full-weathernorth-era5-0p5-1979-2024-24h-v1:
  name: full-weathernorth-era5-0p5-1979-2024-24h-v1
  group_as: era5
  description: Full ERA5 dataset (0.5 deg)
  attribution: ECMWF/C3S
  licence: CC-BY-4.0

  dates:
    start: '1979-01-01T00:00:00'
    end: '2024-12-31T23:00:00'
    frequency: 1d

  input:
    join:
    - mars:
        use_cdsapi_dataset: "reanalysis-era5-complete"
        class: ea
        expver: "0001"
        grid: "0.5 / 0.5"
        area: "90/-180/0/180"  # northern hemisphere
        levtype: sfc
        param:
        - 2t
        - sp
        - 10u
        - 10v
        - msl
    - mars:
        use_cdsapi_dataset: "reanalysis-era5-complete"
        class: ea
        expver: "0001"
        grid: "0.5 / 0.5"
        area: "90/-180/0/180"  # northern hemisphere
        level:
        - 10
        - 250
        - 500
        - 1000
        levtype: pl
        param:
        - z
        - t
        - q
        - u
        - v
    - forcings:
        param:
        - cos_julian_day
        - sin_julian_day
        template: \${input.join.0.mars}
