full-osisaf-1979-2024-24h-v1-sic-south:
  name: full-osisaf-1979-2024-24h-v1-sic-south
  group_as: osisaf
  description: OSISAF sea ice concentration for southern hemisphere
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '1979-01-01T00:00:00'
    end: '2024-12-31T23:00:00'
    frequency: 24h

  preprocessor:
    type: IceNetSIC
    hemisphere: south

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/*.nc
