nbsamp-sicnorth-osisaf-25k-2010-2010-24h-v1:
  name: nbsamp-sicnorth-osisaf-25k-2010-2010-24h-v1
  group_as: osisaf-north
  description: OSISAF sea ice concentration for northern hemisphere - Summer 2010 (August-September)
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '2010-08-01T00:00:00'
    end: '2010-09-30T23:00:00'
    frequency: 1d

  preprocessor:
    type: IceNetSIC
    hemisphere: north

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...name}/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/2010.nc
