nbsamp-era5-0p5-2020-2020-24h-v1-01-04-south:
  name: nbsamp-era5-0p5-2020-2020-24h-v1-01-04-south
  # group_as: era5-south
  description: Small ERA5 dataset for testing (0.5 deg, south)
  attribution: ECMWF/C3S
  licence: CC-BY-4.0

  dates:
    start: '2020-01-01T00:00:00'
    end: '2020-01-05T23:00:00'
    # end: '2020-04-30T23:00:00'
    frequency: 24h

  input:
    anemoi-dataset:
      - dataset: ../zebra_anemoi/data/anemoi/samp-era5-0p5-2020-2020-24h-v1-01-04-south.zarr
        select: [ temp_2m, z_250, z_500 , cos_julian_day, sin_julian_day, msl ]
        rename: [temp_2m: 2t]
      # - example_filter:
      #     input_field: msl  # Example of custom filter
      # - uv_to_ddff:
      #     u_component: u # Name of u wind component (input) variable
      #     v_component: v # Name of v wind component (input) variable
      #     wind_speed: ws # Name of wind speed (output) variable
      #     wind_direction: wdir
  # input:
  # anemoi-dataset:
  #   join:
  #   - dataset: ../zebra_anemoi/data/anemoi/samp2-era5-0p5-2020-2020-24h-v1-01-04-south.zarr
  #     select: [ 2t, 10u, 10v, z_250, z_500 , cos_julian_day, sin_julian_day ]
