nbsamp-era5-0p5-2020-2020-24h-v1-01-04-south:
  name: nbsamp-era5-0p5-2020-2020-24h-v1-01-04-south
  description: Small ERA5 dataset for testing (0.5 deg, south)
  attribution: ECMWF/C3S
  licence: CC-BY-4.0

  dates:
    start: '2020-01-01T00:00:00'
    end: '2020-04-30T23:00:00'
    frequency: 24h

  input:
    anemoi-dataset:
      join:
      - dataset: ${base_path}/data/anemoi/samp-era5-0p5-2020-2020-24h-v1-01-04-south.zarr
        select: [ 2t, z_250, z_500 , 10u, 10v, cos_julian_day, sin_julian_day ]
