nbsamp-sicnorth-osisaf-25k-2018-2018-24h-v1:
  name: nbsamp-sicnorth-osisaf-25k-2018-2018-24h-v1
  group_as: osisaf-north
  description: OSISAF sea ice concentration for northern hemisphere - Summer 2018 (August-September)
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '2018-08-01T00:00:00'
    end: '2018-09-30T23:00:00'
    frequency: 24h

  preprocessor:
    type: IceNetSIC
    hemisphere: north

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...name}/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/2018.nc
