osisaf-sic-south-2019-24h-v1:
  name: osisaf-sic-south-2019-24h-v1
  description: OSISAF data
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '2019-12-01T00:00:00'
    end: '2019-12-31T23:00:00'
    frequency: 24h

  preprocessor:
    type: IceNetSIC
    hemisphere: south

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/2019.nc
