osisaf-sic-south-2020-24h-v1:
  name: osisaf-sic-south-2020-24h-v1
  description: OSISAF data
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '2020-01-01T00:00:00'
    end: '2020-01-31T23:00:00'
    frequency: 24h

  preprocessor:
    type: IceNetSIC
    hemisphere: south

  input:
    netcdf:
      path: "${preprocessor.outputs.path}/2020.nc"
