samp-osisaf-2020-2020-24h-v1-01-04-sic-south:
  name: samp-osisaf-2020-2020-24h-v1-01-04-sic-south
  description: OSISAF sea ice concentration for southern hemisphere
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '2020-01-01T00:00:00'
    end: '2020-04-30T23:00:00'
    frequency: 24h

  preprocessor:
    type: IceNetSIC
    hemisphere: south

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/2020.nc
