samp-sicsouth-osisaf-25k-2017-2019-24h-v1:
  name: samp-sicsouth-osisaf-25k-2017-2019-24h-v1
  group_as: osisaf-south
  description: OSISAF sea ice concentration for southern hemisphere
  attribution: EUMETSAT
  licence: CC-BY-4.0

  dates:
    start: '2017-01-01T00:00:00'
    end: '2019-01-31T23:00:00'
    frequency: 1d

  preprocessor:
    type: IceNetSIC
    hemisphere: south

  input:
    netcdf:
      path: ${base_path}/data/preprocessing/${...name}/${...preprocessor.type}/data/osisaf/${...preprocessor.hemisphere}/siconca/*.nc
