samp-era5-0p5-2020-2020-24h-v1-01-04-south:
  name: samp-era5-0p5-2020-2020-24h-v1-01-04-south
  description: Small ERA5 dataset for testing (0.5 deg, south)
  attribution: ECMWF/C3S
  licence: CC-BY-4.0

  dates:
    start: '2020-01-01T00:00:00'
    end: '2020-04-30T23:00:00'
    frequency: 24h

  input:
    join:
    - mars:
        use_cdsapi_dataset: "reanalysis-era5-complete"
        class: ea
        expver: "0001"
        grid: "0.5 / 0.5"
        area: "0/-180/-90/180"  # southern hemisphere
        levtype: sfc
        param:
        - 2t
        - sp
        - 10u
        - 10v
        - msl
    - mars:
        use_cdsapi_dataset: "reanalysis-era5-complete"
        class: ea
        expver: "0001"
        grid: "0.5 / 0.5"
        area: "0/-180/-90/180"  # southern hemisphere
        level:
        - 10
        - 250
        - 500
        - 1000
        levtype: pl
        param:
        - z
        - t
        - q
        - u
        - v
    - forcings:
        param:
        - cos_julian_day
        - sin_julian_day
        template: \${input.join.0.mars}
