samp-era5-0p5-2020-2020-24h-v1-01-04-south:
  name: samp-era5-0p5-2020-2020-24h-v1-01-04-south
  #group_as: era5-south
  description: Small ERA5 dataset for testing (0.5 deg, south)
  attribution: ECMWF/C3S
  licence: CC-BY-4.0

  dates:
    start: '2020-01-01T00:00:00'
    end: '2020-01-05T23:00:00'
    frequency: 24h

  input:
    pipe:
    - join:
      - mars:
          use_cdsapi_dataset: "reanalysis-era5-complete"
          class: ea
          expver: "0001"
          grid: "0.5 / 0.5"
          area: "0/-180/-90/180"  # southern hemisphere
          levtype: sfc
          param:
          - 2t
          - sp
          - 10u
          - 10v
          - msl
      - mars:
          use_cdsapi_dataset: "reanalysis-era5-complete"
          class: ea
          expver: "0001"
          grid: "0.5 / 0.5"
          area: "0/-180/-90/180"  # southern hemisphere
          level:
          - 250
          - 500
          levtype: pl
          param:
          - z
          - u
          - v
      - forcings:
          param:
          - cos_julian_day
          - sin_julian_day
          template: \${input.pipe.0.join.0.mars}
    - rename:
        param:
          2t: temp_2m
    - uv_to_ddff:
        u_component: u # Name of u wind component (input) variable
        v_component: v # Name of v wind component (input) variable
        wind_speed: ws # Name of wind speed (output) variable
        wind_direction: wdir
    - test_filter:
        input_field: msl  # Example of custom filter
# 
        
# samp-era5-0p5-2020-2020-24h-v1-01-04-south:
#   name: samp-era5-0p5-2020-2020-24h-v1-01-04-south
#   #group_as: era5-south
#   description: Small ERA5 dataset for testing (0.5 deg, south)
#   attribution: ECMWF/C3S
#   licence: CC-BY-4.0

#   dates:
#     start: '2020-01-01T00:00:00'
#     end: '2020-01-05T23:00:00'
#     frequency: 24h

#   input:
#     join:
#     - mars:
#         use_cdsapi_dataset: "reanalysis-era5-complete"
#         class: ea
#         expver: "0001"
#         grid: "0.5 / 0.5"
#         area: "0/-180/-90/180"  # southern hemisphere
#         levtype: sfc
#         param:
#         - 2t
#         - sp
#         - 10u
#         - 10v
#         - msl
#     - mars:
#         use_cdsapi_dataset: "reanalysis-era5-complete"
#         class: ea
#         expver: "0001"
#         grid: "0.5 / 0.5"
#         area: "0/-180/-90/180"  # southern hemisphere
#         level:
#         - 10
#         - 250
#         - 500
#         - 1000
#         levtype: pl
#         param:
#         - z
#         - t
#         - q
#         - u
#         - v
#     # - constants:
#     #     param:
#     #     - cos_julian_day
#     #     - sin_julian_day
#     #     template: ${datasets.samp-era5-0p5-2020-2020-24h-v1-01-04-south.input.join.0.mars.use_cdsapi_dataset}
        