precision: 16-mixed

strategy:
  _target_: ice_station_zebra.training.strategies.ZebraSingleDeviceStrategy
  accelerator: "${..physical.accelerator}"

physical:
  accelerator: auto
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1
