_target_: ice_station_zebra.models.EncodeProcessDecode

name: cnn-unet-cnn

# Each dataset will be encoded into a latent space with these properties
latent_space:
  channels: 20
  shape: [64, 64]

encoder:
  _target_: ice_station_zebra.models.encoders.CNNEncoder

processor:
  _target_: ice_station_zebra.models.processors.UNetProcessor
  filter_size: 3 # Size of the kernel for convolutional layers
  start_out_channels: 64 # Initial number of channels for the first convolutional layer

decoder:
  _target_: ice_station_zebra.models.decoders.CNNDecoder
