_target_: ice_station_zebra.models.EncodeProcessDecode

name: cnn-vit-cnn

encoder:
  _target_: ice_station_zebra.models.encoders.CNNEncoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  latent_space: [192, 192] # Shape of the latent space
  n_layers: 3 # Number of convolutional layers

processor:
  _target_: ice_station_zebra.models.processors.VitProcessor
  patch_size: 16
  emb_dim: 128
  depth: 3
  heads: 4
  mlp_dim: 256
  dropout: 0.3

decoder:
  _target_: ice_station_zebra.models.decoders.CNNDecoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  n_layers: 3 # Number of convolutional layers
