_target_: ice_station_zebra.models.EncodeProcessDecode
mod_antialias: ${..antialias_val}

name: cnn-unet-cnn

encoder:
  _target_: ice_station_zebra.models.encoders.CNNEncoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  latent_space: [128, 128] # Shape of the latent space
  n_layers: 3 # Number of convolutional layers
  antialias: ${..mod_antialias}

processor:
  _target_: ice_station_zebra.models.processors.UNetProcessor
  kernel_size: 3 # Size of the kernel for convolutional layers
  start_out_channels: 64 # Initial number of channels for the first convolutional layer

decoder:
  _target_: ice_station_zebra.models.decoders.CNNDecoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  n_layers: 3 # Number of convolutional layers
  antialias: ${..mod_antialias}
