_target_: ice_station_zebra.models.EncodeProcessDecode

name: encode-ddpm-decode

# Each dataset will be encoded into a latent space with these properties
latent_space:
  channels: 20
  shape: [128, 128]

encoder:
  _target_: ice_station_zebra.models.encoders.CNNEncoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  n_layers: 3 # Number of convolutional layers

processor:
  _target_: ice_station_zebra.models.processors.DDPMProcessor
  timesteps: 1000 # DDPM timesteps

decoder:
  _target_: ice_station_zebra.models.decoders.CNNDecoder
  kernel_size: 3 # Size of the kernel for convolutional layers
  n_layers: 3 # Number of convolutional layers
