_target_: ice_station_zebra.models.EncodeProcessDecode

name: encode-vit-decode

# Each dataset will be encoded into a latent space with these properties
latent_space:
  channels: 20
  shape: [192, 192]

encoder:
  _target_: ice_station_zebra.models.encoders.NaiveLatentSpaceEncoder

processor:
  _target_: ice_station_zebra.models.processors.VitProcessor
  img_size: 192
  patch_size: 16
  emb_dim: 128
  depth: 3
  heads: 4
  mlp_dim: 256
  dropout: 0.3
  start_out_channels: 20 # Initial number of channels
  

decoder:
  _target_: ice_station_zebra.models.decoders.NaiveLatentSpaceDecoder
