_target_: ice_station_zebra.models.EncodeProcessDecode

# Each dataset will be encoded into a latent space with these properties
latent_space:
  channels: 20
  shape: [32, 32]

encoder:
  _target_: ice_station_zebra.models.encoders.LatentSpaceEncoder

processor:
  _target_: ice_station_zebra.models.processors.NullProcessor

decoder:
  _target_: ice_station_zebra.models.decoders.LatentSpaceDecoder
