_target_: ice_station_zebra.models.EncodeProcessDecode

name: encode-unet-decode

# Each dataset will be encoded into a latent space with these properties
latent_space:
  channels: 20
  shape: [128, 128]

encoder:
  _target_: ice_station_zebra.models.encoders.NaiveLatentSpaceEncoder

processor:
  _target_: ice_station_zebra.models.processors.UNetProcessor

decoder:
  _target_: ice_station_zebra.models.decoders.NaiveLatentSpaceDecoder
