_target_: ice_station_zebra.models.EncodeProcessDecode

name: naive-null-naive

# Each dataset will be encoded into a latent space with these properties
latent_space:
  channels: 20
  shape: [128, 128]

encoder:
  _target_: ice_station_zebra.models.encoders.NaiveLinearEncoder

processor:
  _target_: ice_station_zebra.models.processors.NullProcessor

decoder:
  _target_: ice_station_zebra.models.decoders.NaiveLinearDecoder
