---
name: Run tests

# Run workflow on pushes to matching branches
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Python tests
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
      - name: Run pytest
        run: uv run --group dev pytest
      - name: Run mypy
        run: uv run --group dev mypy .
      # For security reasons, PRs created from forks cannot generate PR comments directly
      # (see https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).
      # Instead we need to trigger another workflow after this one completes.
      - name: Generate test coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
      # Save the coverage comment for later use
      # See https://github.com/py-cov-action/python-coverage-comment-action/blob/main/README.md
      - name: Save coverage comment as an artifact
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
