defaults:
  - datasets:
    - demo_sicnorth_osisaf_25k_2017_2019_24h_v1
    - demo_weathernorth_era5_0p5_2017_2019_24h_v1
  - evaluate: default
  - loggers:
    - wandb
  - model: naive_unet_naive
  - predict: osisaf-north
  - split: demo_dataset
  - train: default
  - _self_

base_path: /bask/projects/v/vjgo8416-ice-frcst/shared/zebra/
