defaults:
  - base
  - datasets:
    - osisaf-sic-north-2003-08-24h-v1
    - osisaf-sic-north-2010-08-24h-v1
    - osisaf-sic-north-2018-08-24h-v1
  - whale_telemetry
  - visualization
  - evaluate: default
base_path: /your/path/to/data
