defaults:
  - base
  - datasets:
    - nbsamp_sicnorth_osisaf_25k_2003_2003_24h_v1
    - nbsamp_sicnorth_osisaf_25k_2010_2010_24h_v1
    - nbsamp_sicnorth_osisaf_25k_2018_2018_24h_v1
  - notebooks:
    - whale_telemetry_csv
    - whale_visualisation
  - _self_
