defaults:
  - datasets:
    - era5-0d5-south-2019-12-24h-v1
    - era5-0d5-south-2020-01-24h-v1
    - osisaf-sic-south-2019-12-24h-v1
    - osisaf-sic-south-2020-01-24h-v1
  - model: null_processor
  - train: default
  - _self_

base_path: /bask/projects/v/vjgo8416-ice-frcst/shared/zebra/
