defaults:
  - datasets:
    - era5-o48-2020-01-6h-v1
  - _self_

data_path: /bask/projects/v/vjgo8416-ice-frcst/shared/prototype_data/
test:
  some_test_parameter: 1
train:
  osisaf_path: "/bask/projects/v/vjgo8416-ice-frcst/shared/prototype_data/osisaf/south/siconca/2000"
