defaults:
  - datasets:
    - samp-era5-0d5-2020-24h-01-04-south-v1
    - samp-osisaf-sic-2020-24h-01-04-south-v1
  - evaluate: default
  - loggers:
    - wandb
  - model: encode_null_decode
  - predict: osisaf-south
  - split: default
  - train: default
  - _self_

base_path: /bask/projects/v/vjgo8416-ice-frcst/shared/zebra/
